---
name: branch-naming

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: branch-naming-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-branch-naming:
    name: check-branch-naming
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: check branch name
        id: branch-name
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          elif [[ "$GITHUB_REF" == refs/pull/*/merge ]]; then
            BRANCH_NAME=$(echo $GITHUB_REF | sed -n 's|refs/pull/\([0-9]\+\)/merge|PR-\1|p')
          else
            BRANCH_NAME="unknown"
          fi
          echo "Current branch: $BRANCH_NAME"
          valid_branch_regex="${{ vars.VALID_BRANCH_REGEX }}"
          
          if [[ $BRANCH_NAME =~ $valid_branch_regex ]]; then
            echo "Branch name: $BRANCH_NAME is valid"
          else
            echo "Branch name: $BRANCH_NAME is not valid"
            exit 1
          fi